name: CD / Run / deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag next-snake:${{ github.run_number }}

      - name: Stop and remove existing container
        run: |
          docker stop next-snake || true
          docker rm next-snake || true

      - name: Run Docker container
        run: docker run -d -p 2411:3000 --name next-snake next-snake:${{ github.run_number }}